add-homepage
Rutger505/Geoprofs pull request #14
Opened 2024-11-08 09:00 UTC by Rutger505

2024-11-20 15:57 UTC, Rutger505 commented
To do: Make header responsive, finish tests for header

2024-11-27 19:46 UTC, Rutger505 commented
Header takes up 1/3 of page...

2024-11-27 19:51 UTC, Rutger505 commented on front-end/src/app/layout.tsx
> +          "min-h-screen grid grid-cols-[auto_*]",
```suggestion
          "min-h-screen grid grid-rows-[auto_1fr]",
```

2024-11-28 10:48 UTC, JakevdKolk requested changes
testen gefaald

2024-11-28 11:09 UTC, JakevdKolk approved these changes
tests doen het

2024-11-28 11:09 UTC, merged