add-complete-account-form
Rutger505/Geoprofs pull request #40
Opened 2024-12-18 12:32 UTC by Rutger505

2024-12-18 13:21 UTC, JakevdKolk requested changes
Misschien naar development mergen inplaats van naar main...

2025-01-02 17:13 UTC, Rutger505 commented
Ik heb de pull request terug op draft gezet omdat: Er is een raar probleem met authenticatie ik denk dat het gaat door het niet setten van cookies in de put request van complete account. Dit zorgt ervoor dat je wel ingelogt bent bij next.js maar niet bij laravel. Ik ga eerst authenticatie weg halen bij laravel voordat ik verder ga met deze pull.

2025-01-04 13:16 UTC, JakevdKolk approved these changes
ziet er goed uit

2025-01-04 13:18 UTC, JakevdKolk approved these changes
ziet er goed uit

2025-01-04 13:20 UTC, merged